apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: weatherforecast-csharp
  namespace: backend
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: weatherforecast-csharp
    #apis.apps.tanzu.vmware.com/register-api: true
spec:
  source:
    git:
      url: https://github.com/fabianbrash/weatherforecast-csharp.git
      ref:
        branch: main
  #params:
    #- name: api_descriptor
      #value:
        #type: openapi
        #location:
          #path:
        #owner: team-csharp
        #description: "A set pf API endpoint to manage the resources with the weather app."
